"""One interface per app. Live and fake implementations must match these signatures."""
class CRM:
    def search(self, email) -> dict | None: ...
    def create(self, a) -> dict: ...
    def update(self, contact_id, fields) -> dict: ...
    def create_deal(self, a) -> dict: ...
class Gmail:
    def fetch_unread(self) -> list[dict]: ...      # [{id, from, subject, body, thread_id}]
    def send(self, a) -> dict: ...
class Slack:
    def post_approval(self, a) -> dict: ...
    def post_message(self, a) -> dict: ...
class Calendar:
    def free_slots(self, preferred=None) -> list[str]: ...
    def create_event(self, a) -> dict: ...

class Apps:
    def __init__(self, crm, gmail, slack, calendar):
        self.crm, self.gmail, self.slack, self.calendar = crm, gmail, slack, calendar
